CREATE TABLE cliente (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome varchar(60) not null,
    email varchar(255) not null,
    telefone varchar(20) not null,

    primary key(id)
);